# Generated by Django 5.2.11 on 2026-02-11 23:40

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introducao', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
            ],
            options={
                'verbose_name': 'Página do Blog',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='contato@virtu.com.br', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(default='(11) 99999-9999', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('copyright_texto', models.CharField(default='© 2025 Todos os direitos reservados - virtú', max_length=200, verbose_name='Texto do Copyright')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='StatusEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('cor_badge', models.CharField(default='#C9A96E', max_length=7, verbose_name='Cor do Badge')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Status de Empreendimento',
                'verbose_name_plural': 'Status de Empreendimentos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('data', models.DateField(verbose_name='Data de Publicação')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('conteudo', wagtail.fields.RichTextField(verbose_name='Conteúdo')),
                ('autor', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('imagem_destaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de Destaque')),
            ],
            options={
                'verbose_name': 'Post do Blog',
                'ordering': ['-data'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContatoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_titulo', models.CharField(default='Fale Conosco', max_length=200, verbose_name='Título')),
                ('hero_subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('form_titulo', models.CharField(default='Envie sua mensagem', max_length=100, verbose_name='Título do Formulário')),
                ('hero_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
            ],
            options={
                'verbose_name': 'Página de Contato',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome (autor)')),
                ('cargo', models.CharField(default='morador(a)', max_length=100, verbose_name='Cargo/Função')),
                ('texto', models.TextField(verbose_name='Texto do Depoimento')),
                ('avaliacao', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação (1-5)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-destaque', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, choices=[('lazer', 'Lazer'), ('seguranca', 'Segurança'), ('sustentabilidade', 'Sustentabilidade'), ('conforto', 'Conforto'), ('localizacao', 'Localização'), ('infraestrutura', 'Infraestrutura'), ('outro', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('icone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpreendimentoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('descricao_curta', models.TextField(blank=True, verbose_name='Descrição Curta')),
                ('descricao', wagtail.fields.RichTextField(blank=True, verbose_name='Descrição Completa')),
                ('localizacao', models.CharField(blank=True, max_length=300, verbose_name='Localização')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('preco_a_partir', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preço a partir de')),
                ('metragem_a_partir', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem a partir de')),
                ('dormitorios', models.CharField(blank=True, max_length=50, verbose_name='Dormitórios')),
                ('caracteristicas_resumo', models.CharField(blank=True, max_length=200, verbose_name='Características Resumo')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do Vídeo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade', verbose_name='Cidade')),
                ('diferenciais', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.diferencial', verbose_name='Diferenciais')),
                ('imagem_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
                ('imagem_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem Principal (Card)')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo do Empreendimento')),
                ('video_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail do Vídeo')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'ordering': ['ordem', '-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AndamentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título/Etapa')),
                ('percentual', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentual Concluído')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos_obra', to='core.empreendimentopage')),
            ],
            options={
                'verbose_name': 'Etapa do Cronograma',
                'verbose_name_plural': 'Etapas do Cronograma',
            },
        ),
        migrations.CreateModel(
            name='EmpreendimentosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('hero_subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('form_titulo', models.CharField(default='Cadastre-se e saiba mais!', max_length=100, verbose_name='Título do Formulário')),
                ('secao_projetos_titulo', models.CharField(default='Conheça nossos projetos', max_length=100, verbose_name='Título da Seção de Projetos')),
                ('hero_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
            ],
            options={
                'verbose_name': 'Página de Empreendimentos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FotoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('data_captura', models.DateField(blank=True, null=True, verbose_name='Data da Captura')),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_obra', to='core.empreendimentopage')),
            ],
            options={
                'verbose_name': 'Foto da Obra',
                'verbose_name_plural': 'Fotos da Obra',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição/Legenda')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='core.empreendimentopage')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_titulo', models.CharField(default='O seu futuro é o nosso propósito', max_length=200, verbose_name='Título do Hero')),
                ('secao_futuro_titulo', models.CharField(default='Pensamos no futuro', max_length=100, verbose_name='Título da Seção')),
                ('secao_futuro_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('banner_institucional_texto', models.CharField(blank=True, default='Na virtú acreditamos que não há um único destino.', max_length=500, verbose_name='Texto do Banner')),
                ('secao_jornada_titulo', models.CharField(default='Da visão à realidade', max_length=100, verbose_name='Título da Jornada')),
                ('etapas_jornada', wagtail.fields.StreamField([('etapa', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Número', 'max_length': 2}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Título', 'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Descrição'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Ícone', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('numero', 0), ('titulo', 1), ('descricao', 2), ('icone', 3)]], {})}, verbose_name='Etapas')),
                ('banner_destaque_texto', models.CharField(blank=True, max_length=300, verbose_name='Texto do Banner')),
                ('secao_depoimentos_titulo', models.CharField(default='depoimentos reais', max_length=100, verbose_name='Título da Seção de Depoimentos')),
                ('cta_titulo', models.CharField(default='Vamos conversar sobre o seu futuro!', max_length=200, verbose_name='Título do CTA')),
                ('cta_botao_texto', models.CharField(default='Conheça mais', max_length=50, verbose_name='Texto do Botão')),
                ('banner_institucional_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Banner Institucional')),
                ('empreendimento_destaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.empreendimentopage', verbose_name='Empreendimento em Destaque')),
                ('hero_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
                ('secao_futuro_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Página Inicial',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('pagina_origem', models.CharField(blank=True, max_length=500, verbose_name='Página de Origem')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em Contato'), ('qualificado', 'Qualificado'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=50, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empreendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.empreendimentopage', verbose_name='Empreendimento de Interesse')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('site', models.URLField(blank=True, verbose_name='Site')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
        migrations.AddField(
            model_name='empreendimentopage',
            name='parceiros',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.parceiro', verbose_name='Parceiros'),
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Planta')),
                ('dormitorios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº de Dormitórios')),
                ('metragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metragem (m²)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('caracteristicas', models.TextField(blank=True, help_text='Uma característica por linha', verbose_name='Características')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem da Planta')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='core.empreendimentopage')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='SobreNosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_titulo', models.CharField(default='a virtú', max_length=100, verbose_name='Título')),
                ('historia_titulo', models.CharField(default='nossa história', max_length=100, verbose_name='Título')),
                ('historia_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('video_titulo', models.CharField(default='vídeo institucional virtú', max_length=200, verbose_name='Título')),
                ('video_url', models.URLField(blank=True, verbose_name='URL do Vídeo')),
                ('missao_titulo', models.CharField(default='missão', max_length=50, verbose_name='Título')),
                ('missao_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('visao_titulo', models.CharField(default='visão', max_length=50, verbose_name='Título')),
                ('visao_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('valores_titulo', models.CharField(default='valores', max_length=50, verbose_name='Título')),
                ('valores_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('politica_titulo', models.CharField(default='política de qualidade', max_length=100, verbose_name='Título')),
                ('politica_texto', wagtail.fields.RichTextField(blank=True, verbose_name='Texto')),
                ('cta_titulo', models.CharField(default='Pronto para fazer parte de nossa história?', max_length=200, verbose_name='Título do CTA')),
                ('cta_subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('cta_botao_texto', models.CharField(default='Entrar em contato', max_length=50, verbose_name='Texto do Botão')),
                ('cta_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do CTA')),
                ('hero_imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do Hero')),
                ('video_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Thumbnail')),
            ],
            options={
                'verbose_name': 'Página Sobre Nós',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='empreendimentopage',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statusempreendimento', verbose_name='Status de Vendas'),
        ),
    ]
